
target("Dx12lib")
    set_languages("c++latest")
    set_group("Dx12Renderer")
    set_kind("static")
    add_rules("utils.bin2c", {extensions = {".hlsl"}})
    add_cxflags("/MP")
    add_defines("_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING", {public=true})
    add_headerfiles("**.h")
    add_headerfiles("**.hpp")
    add_files("**.cpp")
    add_files("Texture/*.hlsl")
    add_includedirs(DX12RENDERER_DIR, {public=true})
    add_includedirs(DX12RENDERER_EXT_DIR, {public=true})
    local pixLibDir = path.join(DX12RENDERER_EXT_DIR, "WinPixEventRuntime", "winpixeventruntime.1.0.22081000");
    add_includedirs(path.join(pixLibDir, "Include", "WinPixEventRuntime"), {public=true})
    add_linkdirs(path.join(pixLibDir, "bin", "x64"))
    add_links("d3dcompiler")
    add_links("D3D12")
    add_links("dxgi")
    add_links("WinPixEventRuntime")
    add_deps("DirectXTex")
target_end()

