add_rules("mode.debug", "mode.release", "mode.releasedbg")
target("Math")
    set_warnings("all", "error")
    set_kind("static")
    set_group("Dx12Renderer")
    add_headerfiles("**.h")
    add_headerfiles("**.hpp")
    add_headerfiles("**.inc")
    add_headerfiles("**.inl")
    add_files("**.cpp")
target_end()